### ISSUE TITLE
How to use pcan on windows 10?

### ISSUE THREAD

**Issue by zhangshengping** [UAVCAN/yakut#24]
is there some example on how to use pcan on windows 10?
how to set enverment var on windows?

**Comment by pavel-kirienko** [comment]
> is there some example on how to use pcan

Yes:

- https://pyuavcan.readthedocs.io/en/stable/api/pyuavcan.transport.can.media.pythoncan.html
- https://github.com/UAVCAN/yakut#communicating

The tutorial will help with the basics: https://pyuavcan.readthedocs.io/en/stable/pages/demo.html

>how to set enverment var on windows?

Install PowerShell and use it: https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7.1

```powershell
$env:UAVCAN__CAN__IFACE="pcan:PCAN_USBBUS1"
```

**Comment by pavel-kirienko** [comment]
This may also help:

https://youtu.be/dYRmw8kL04c
