### ISSUE TITLE
Is there a way to filter out certain CAN IDs in yakut monitor?

### ISSUE THREAD

**Issue by pepeRossRobotics** [UAVCAN/yakut#41]
Hello might be a dump question, but I have a CAN bus that has UAVCAN and non UAVCAn devices. I know this is not optimal and can cause PnP issues, but I have no other way around it.

I would like to know if it is possible to filter out the other nodes in the yakut monitor without filtering them form socket can, as I use the other nodes for other hardware interfaces.

Any pointer in how to deal with this are very welcome

**Comment by pavel-kirienko** [comment]
Take a look:

https://github.com/UAVCAN/pyuavcan/blob/510feed778df657d64f4054912f15f490df9acb4/pyuavcan/transport/can/_tracer.py#L75-L77

https://github.com/UAVCAN/yakut/blob/8864c834d89d5576f872a0bd5eee37ccf43047f3/yakut/cmd/monitor/_iface.py#L82-L86

Frames that are not valid UAVCAN v1 frames are supposed to be simply dropped without incrementing the error counter (unless these non-UAVCAN frames happen to look quite like valid UAVCAN frames, which is rarely the case). So I suggest that you simply use Yakut as usual with no regard for your other nodes/frames. Is this not working in your case?

**Comment by pepeRossRobotics** [comment]
Hello Pavel,
Currently I have 4 non UAVCAN devices, publihsing at a 50Hz reate each and this is how the error counter in Yakut looks
![image](https://user-images.githubusercontent.com/66112254/152764182-ef0e77f0-c948-4c4f-ac2e-8c93a7dfaa40.png)

**Comment by pavel-kirienko** [comment]
If the frames look like UAVCAN frames, it's going to be difficult or impossible to find a generic solution to this. Can you please share the format of those frames or maybe just post a short dump?

Also, you are using an old version of Yakut, please update.

**Comment by pepeRossRobotics** [comment]
[VESC 6 CAN Formats. Version PDF Free Download.pdf](https://github.com/UAVCAN/yakut/files/8016054/VESC.6.CAN.Formats.Version.PDF.Free.Download.pdf)


This is a document explaining the CAN frames.

**Comment by pepeRossRobotics** [comment]
https://vesc-project.com/sites/default/files/imce/u15301/VESC6_CAN_CommandsTelemetry.pdf

Above you can see the VESC CAN frame structure.

**Comment by pavel-kirienko** [comment]
Okay, indeed, this could cause collisions. It is generally unsafe to operate UAVCAN on the same bus with the protocol you shared because it may cause data corruption (if VESC and a UAVCAN node publish frames with the same ID but different payloads). It is quite unlikely but that is a separate story.

The best quick solution I can recommend is to ignore the error counter. The fact that it keeps incrementing is the correct and expected behavior because the bus is technically malfunctioning.
