### ISSUE TITLE
`yakut compile` deletes directory initially

### ISSUE THREAD

**Issue by davidlenfesty** [UAVCAN/yakut#9]
It seems that it will delete the output directory first, so if the DSDL namespace you're working on is directly in the working directory, it will delete the directory, and have no files to work on, quitting. It will output a warning, but only after deleting the namespace.

IMO the warning should be changed to an error, with a suggestion to nest the namespaces down a level, if the current behaviour of clearing the output directory is to be kept.

Simple reproduction
```
git clone https://github.com/UAVCAN/public_regulated_data_types
yakut compile public_regulated_data_types
```

**Comment by pavel-kirienko** [comment]
It was fixed about two months ago: https://github.com/UAVCAN/pyuavcan/pull/138

Please make sure you are running the latest software

**Comment by davidlenfesty** [comment]
1. I don't get this issue in pyuavcan, which signifies it's a different problem somehow
2. I've reproduced it with fully updated packages in a fresh venv

```
pydsdl == 1.10.1
pyuavcan == 1.1.3
yakut == 0.1.5
```

The issue is here: https://github.com/UAVCAN/yakut/blob/9aee303db539e07b023458c51bf7325e744f0f6c/yakut/cmd/compile.py#L179

**Comment by pavel-kirienko** [comment]
I somehow managed to introduce the same bug in two different places. Sigh. I just fixed it in the orchestration branch, let me put up a PR.
